config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  resources :users, only: [:show, :edit, :create, :update]
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many_attached :images
  belongs_to :user

  with_options presence: true do
     validates :title
     validates :content
     validates :images
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image

  with_options presence: true do
    validates :username
    validates :email
  end

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
    if @post.user != current_user
      redirect_to post_path(@post), alert: "不正なアクセスです"
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post), notice: "投稿完了です！"
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "投稿を更新しました！"
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path, notice: "投稿を削除しました！"
    else
      redirect_to root_path, alert: "投稿を削除できませんでした。。"
    end
  end

  private
  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :address, :content, images:[])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :find_user, only: [:show, :edit, :update]

  def show
  end

  def edit
    if @user != current_user
      redirect_to users_path, alert: "不正なアクセスです"
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: "プロフィール情報を更新しました"
    else
      render :edit
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :profile, :image)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/notifications' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/posts/edit.html.erb
<% if @post.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model: @post do |form|  %>
          <div class="field">
            <%= form.label :title, "ビーチ名", class: "label"  %>
            <%= form.text_field :title, class: "input" %>
          </div>
          
          <div class="field">
            <%= form.label :address, "市・エリア", class: "label"  %>
            <%= form.text_field :address, class: "input" %>
          </div>
          
          <div class="field">
            <%= form.label :content, "おすすめポイント", class: "label"  %>
            <%= form.text_area :content, class: "textarea" %>
          </div>

          <div class="field">
            <%= form.label :images, "Photo", class: "label" %>
            <%= form.file_field :images, multiple: true, class: "input" %>
          </div>
        
          <%= form.submit "更新する", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @posts.each do |post| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to post_path(post) do %>
                  <% if post.images.attached? %>
                    <div class="images">
                      <% post.images.each do |image| %>
                        <%= image_tag image %>
                      <% end %>
                    </div>
                  <% end %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to post.title, post_path(post) %></div>
                </div>
              </div>
              <div class="media-left">
                <figure class="image is-50x50">
                    
                </figure>
              </div>
              <div class="content">
                <%=link_to post.user.username, user_path(post.user) %>
              </div>
              <div class="content">
                <time><%= post.updated_at.strftime("%Y-%m-%d") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/posts/new.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">ビーチ登録</h1>
    </div>
  </div>
</section>

<% if @post.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model: @post do |form|  %>
          <div class="field">
            <%= form.label :title, "ビーチ名", class: "label"  %>
            <%= form.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= form.label :address, "市・エリア", class: "label"  %>
            <%= form.text_field :address, class: "input" %>
          </div>

          <div class="field">
            <%= form.label :content, "おすすめポイント", class: "label"  %>
            <%= form.text_area :content, class: "textarea" %>
          </div>

          <div class="field">
            <%= form.label :images, "Photo", class: "label" %>
            <%= form.file_field :images, multiple: true, class: "input" %>
          </div>
        
          <%= form.submit "投稿する", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <% if @post.images.attached? %>
                <div class="images">
                  <% @post.images.each do |image| %>
                    <%= image_tag image %>
                  <% end %>
                </div>
              <% end %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @post.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>おすすめポイント</th>
                </tr>
                <tr>
                  <td><%= simple_format @post.content %></td>
                </tr>
              </table>
              <% if @post.user.id == current_user.id %>
                <%= link_to "編集", edit_post_path, class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
            <%= @post.title %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @post.address %>
            </p>
          </div>
          <%= link_to user_path(@post.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @post.user.username %> のページ
          <% end %>
        </article>
      </div>
    </div>
  </div>
</section>

app/views/shared/_footer.html.erb
<div id="footer">
  <p>©️ 2021 Yuri Wada Portfolio</p>
</div>

app/views/shared/_header.html.erb
<nav class="navbar is-warning">
  <div class="navbar-brand">
    <div class="logo">
      <%= link_to posts_path do %>
        <%= image_tag 'cooltext391850246700560.png' %>
      <% end %>
    </div>
  </div>

  <% if user_signed_in? %>
    <div id="navbarExampleTransparentExample" class="navbar-menu">
      <div class="navbar-item">
        <%= link_to "ビーチ一覧", posts_path, class: "navbar-item button is-warning is-light" %>
      </div>
      <div class="navbar-item">
        <%= link_to "新規投稿", new_post_path, class: "navbar-item button is-warning is-light" %>
      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light" %>
            </p>
            <p class="control">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div id="navbarExampleTransparentExample" class="navbar-menu">
      <div class="navbar-item">
        <%= link_to "ビーチ一覧", posts_path, class: "navbar-item button is-warning is-light" %>
      </div>
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
            </p>
            <p class="control">
              <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</nav>

app/views/shared/_notifications.html.erb
<% if flash[:notice] %>
  <div class="notification is-info">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="notification is-danger">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>

app/views/users/edit.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <section class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model: @user, local: true do |form| %>
          <div class="field">
            <%= form.label :username, "ユーザー名", class: "label" %>
            <%= form.text_field :username, class: "input" %>
          </div>

        <div class="field">
          <%= form.label :email, "メールアドレス", class: "label" %>
          <%= form.text_field :email, class: "input" %>

        <div class="field"> 
          <%= form.label :profile, "プロフィール", class: "label"  %>
          <%= form.text_area :profile, class: "textarea" %>
        </div>

        <div class="field">
            <%= form.label :image, "プロフィール画像", class: "label" %>
            <%= form.file_field :image, class: "input" %>
          </div>

          <%= form.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <% if @user.image.attached? %>
                <%= image_tag @user.image, class: "profile_image is-rounded" %>
              <% end %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.posts.each do |post| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to post_path do %>
                  <% if post.images.attached? %>
                    <div class="images">
                      <% post.images.each do |image| %>
                        <%= image_tag image %>
                      <% end %>
                    </div>
                  <% end %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to post_path, class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-anchor" aria-hidden="true"></i>
                    </span>
                    <%= post.title %>
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_post_path, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      編集
                    <% end %>
                    <%= link_to post_path, method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      削除
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= post.updated_at.strftime("%Y-%m-%d") %></time>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/welcome/index.html.erb
<section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <p>
          <strong class="is-size-1" style="font-family: cursive;">recipegram</strong>
        </p>
      </div>
      <div class="columns is-centered">
        <div class="column is-5">
          <br>
          <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-fullwidth" %>
          <br>
          <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-fullwidth" %>
        </div>
      </div>
    </div>
  </article>
  <br>
  <div class="columns is-centered">
    <div class="column">
      <figure>
        <div class="main-image"></div>
      </figure>
    </div>
  </div>
</section>